### ISSUE TITLE
Doesn't appear to work

### ISSUE THREAD

**Issue by postal2600** [bkbooth/color-gutter#10]
I'm running Atom v0.187.0 under Ubuntu 14.04 LTS and when I open a CSS file with colors all over it I see no colors in the gutter.

Does this work only for LESS / SASS, or should it work also for plain old CSS ?

**Comment by postal2600** [comment]
Tested on WIndows and it doesn't work as well. This time, I got also some hints about why:

```
keymaps\color-gutter.cson
Use the `atom-workspace` tag instead of the `workspace` class.

stylesheets\color-gutter.less
Use the `atom-text-editor` tag instead of the `editor` class.

Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension. If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.
```

**Comment by bkbooth** [comment]
Hi, thanks for trying to use my plugin. I wrote it in a flurry of trying to get into using Atom as my primary editor and it's since been neglected. I need to work out if I'm going to fix it up again or just pull it down. I'll take a look into this problem later today.

**Comment by postal2600** [comment]
If it's all the same to you, I can try to fix this issue and create a pull request

**Comment by bkbooth** [comment]
Nevermind, it appears I merged a couple of pull requests that I think should fix the issue, I just need to push a release I think... now to remember how to do that with apm again.

**Comment by postal2600** [comment]
Great! looking forward to the update :+1:

**Comment by bkbooth** [comment]
I just published the recently merged changes but it's still not working, there's been a few breaking changes in atom since I last worked on it. The 'Deprecation Cop' has details that should help fixing the issues. I don't have time to look at it right now, but if you do feel free to fix it and make a pull request.

**Comment by surdu** [comment]
Just realized it's written in coffee. Sorry, I don't know it and I don't plan to learn it :disappointed:

**Comment by bkbooth** [comment]
Yeah, I'm not a big fan of CoffeeScript either, I did a crash-course in it because everything Atom was CoffeeScript (you could use pure JS but it seemed like it was being discouraged at the start). I'll take a look into this hopefully over the weekend and get a fix pushed out.
