### ISSUE TITLE
Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

### ISSUE THREAD

**Issue by desduvauchelle** [bkbooth/color-gutter#11]
In stylesheets/color-gutter.less: Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.
If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

**Comment by bkbooth** [comment]
Thanks for the bug report. I've fixed this particular issue, but there's a number of issues preventing this extension from working at the moment. Just working on fixing them all before pushing an update.
